name: Publish Auto

on:
  push:
    branches:
      # No canary deploys
      - "main"
      - "next"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    name: Make a release and publish to NPM
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: smtp-relay
          tags: release
          archs: amd64, arm64
          dockerfiles: |
            ./Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: loopingz
          password: ${{ secrets.DOCKER_HUB }}
          
      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Create release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}