name: Build docker
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Make container
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

        
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: smtp-relay
          tags: release
          archs: amd64, arm64
          dockerfiles: |
            ./Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: loopingz
          password: ${{ secrets.DOCKER_HUB }}
